using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HoofMark.CSharpTemplating.Core;

/// <summary>
/// Resolves NuGet package assemblies by reading the project's <c>project.assets.json</c>
/// file generated by <c>dotnet restore</c>. No network access or separate cache required —
/// assemblies are resolved directly from the NuGet global packages folder.
/// </summary>
public sealed class NuGetResolver
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        AllowTrailingCommas = true,
        ReadCommentHandling = JsonCommentHandling.Skip
    };

    /// <summary>
    /// Resolves managed and native assemblies for the requested packages from
    /// the project's assets file.
    /// </summary>
    /// <param name="assetsFilePath">
    /// Full path to the <c>project.assets.json</c> file (typically in the project's <c>obj/</c> folder).
    /// </param>
    /// <param name="packageFilter">
    /// Package IDs to include. Only these packages (and their transitive dependencies
    /// as resolved by NuGet) will be returned. Case-insensitive.
    /// </param>
    /// <param name="targetFramework">
    /// The target framework moniker to resolve assemblies for, e.g. "net10.0".
    /// If null, the first target in the assets file is used.
    /// </param>
    /// <returns>
    /// A <see cref="NuGetResolutionResult"/> containing paths to managed assemblies
    /// (for Roslyn references and the load context) and native libraries (for
    /// unmanaged P/Invoke resolution).
    /// </returns>
    public NuGetResolutionResult Resolve(
        string assetsFilePath,
        IEnumerable<string> packageFilter,
        string? targetFramework = null)
    {
        if (!File.Exists(assetsFilePath))
            throw new NuGetResolutionException(
                $"Assets file not found: '{assetsFilePath}'. " +
                $"Run 'dotnet restore' on the project to generate it.");

        var json = File.ReadAllText(assetsFilePath);
        AssetsFile assets;
        try
        {
            assets = JsonSerializer.Deserialize<AssetsFile>(json, JsonOptions)
                     ?? throw new NuGetResolutionException(
                         $"Failed to parse assets file: '{assetsFilePath}'.");
        }
        catch (JsonException ex)
        {
            throw new NuGetResolutionException(
                $"Failed to parse assets file '{assetsFilePath}': {ex.Message}", ex);
        }

        const int SupportedVersion = 3;
        if (assets.Version != SupportedVersion)
            throw new NuGetResolutionException(
                $"Unsupported project.assets.json format version '{assets.Version}' in '{assetsFilePath}'. " +
                $"cstemplate supports version {SupportedVersion}. This may indicate a NuGet tooling upgrade " +
                $"has changed the assets file format. Please check for an updated version of cstemplate.");

        var targetKey = ResolveTargetKey(assets, targetFramework, assetsFilePath);

        if (!assets.Targets.TryGetValue(targetKey, out var target))
            throw new NuGetResolutionException(
                $"Target '{targetKey}' not found in '{assetsFilePath}'. " +
                $"Run 'dotnet restore' to regenerate the assets file.");

        // Build a set of package IDs to include (case-insensitive)
        var filter = new HashSet<string>(packageFilter, StringComparer.OrdinalIgnoreCase);

        if (filter.Count == 0)
            return NuGetResolutionResult.Empty;

        // Collect all transitive dependencies of the filtered packages
        var included = ResolveTransitiveClosure(target, filter);

        // Resolve assembly paths from the global packages folders
        var packageFolders = assets.PackageFolders.Keys.ToList();

        var rids         = GetRuntimeIdentifierCandidates();
        var managedPaths = ResolveAssemblyPaths(target, assets.Libraries, included, packageFolders, rids);
        var nativePaths  = ResolveNativePaths(target, assets.Libraries, included, packageFolders, rids);

        return new NuGetResolutionResult(managedPaths, nativePaths);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private static string ResolveTargetKey(
        AssetsFile assets,
        string? targetFramework,
        string assetsFilePath)
    {
        if (assets.Targets.Count == 0)
            throw new NuGetResolutionException(
                $"No targets found in '{assetsFilePath}'. " +
                $"Run 'dotnet restore' to regenerate the assets file.");

        if (targetFramework == null)
            return assets.Targets.Keys.First();

        // Match by short name (e.g. "net10.0") against full key
        // The key may be just "net10.0" or "net10.0/win-x64" etc.
        var match = assets.Targets.Keys
            .FirstOrDefault(k => k.StartsWith(targetFramework, StringComparison.OrdinalIgnoreCase));

        return match ?? assets.Targets.Keys.First();
    }

    /// <summary>
    /// Walks the dependency graph to find all transitive dependencies of the
    /// requested packages. Returns the full set of package keys to include.
    /// </summary>
    private static HashSet<string> ResolveTransitiveClosure(
        Dictionary<string, TargetPackage> target,
        HashSet<string> rootFilter)
    {
        var included = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var queue    = new Queue<string>();

        // Seed the queue with the directly requested packages
        foreach (var entry in target)
        {
            // entry key is "PackageId/version"
            var id = entry.Key.Split('/')[0];
            if (rootFilter.Contains(id))
                queue.Enqueue(entry.Key);
        }

        while (queue.Count > 0)
        {
            var key = queue.Dequeue();

            if (!included.Add(key))
                continue; // already visited

            if (!target.TryGetValue(key, out var pkg) || pkg.Dependencies == null)
                continue;

            // Enqueue all dependencies
            foreach (var dep in pkg.Dependencies)
            {
                // Find the full "DepId/version" key in the target
                var depKey = target.Keys
                    .FirstOrDefault(k => k.StartsWith(dep.Key + "/",
                        StringComparison.OrdinalIgnoreCase));

                if (depKey != null)
                    queue.Enqueue(depKey);
            }
        }

        return included;
    }

    /// <summary>
    /// Resolves absolute dll paths for all included packages by looking them
    /// up in the NuGet package folders declared in the assets file.
    /// </summary>
    private static IReadOnlyList<string> ResolveAssemblyPaths(
        Dictionary<string, TargetPackage> target,
        Dictionary<string, LibraryEntry> libraries,
        HashSet<string> included,
        List<string> packageFolders,
        IReadOnlyList<string> rids)
    {
        var paths = new List<string>();

        foreach (var key in included)
        {
            if (!target.TryGetValue(key, out var pkg))
                continue;

            // Union compile, runtime, and RID-specific managed runtime refs.
            // Some packages only appear in runtime (e.g. System.Configuration.ConfigurationManager)
            // or only in runtimeTargets (e.g. the win-specific Microsoft.Data.SqlClient.dll).
            var refs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (pkg.Compile != null) refs.UnionWith(pkg.Compile.Keys);
            if (pkg.Runtime != null) refs.UnionWith(pkg.Runtime.Keys);

            // Add RID-specific managed dlls from runtimeTargets, preferring the best matching RID
            if (pkg.RuntimeTargets != null)
            {
                var bestRid = rids.FirstOrDefault(rid =>
                    pkg.RuntimeTargets.Any(rt =>
                        rt.Value.AssetType == "runtime" &&
                        string.Equals(rt.Value.Rid, rid, StringComparison.OrdinalIgnoreCase)));

                if (bestRid != null)
                {
                    foreach (var rt in pkg.RuntimeTargets)
                    {
                        if (rt.Value.AssetType == "runtime" &&
                            string.Equals(rt.Value.Rid, bestRid, StringComparison.OrdinalIgnoreCase))
                            refs.Add(rt.Key);
                    }
                }
            }

            if (refs.Count == 0)
                continue;

            // Find the library entry for path info
            if (!libraries.TryGetValue(key, out var lib))
                continue;

            // lib.Path is something like "humanizer.core/2.14.1"
            var packagePath = lib.Path?.Replace('/', Path.DirectorySeparatorChar)
                              ?? key.Replace('/', Path.DirectorySeparatorChar);

            // Try each package folder until we find the dll
            foreach (var assemblyRef in refs)
            {
                // compileRef is e.g. "lib/net6.0/Humanizer.dll" or "_._" (placeholder)
                if (assemblyRef.EndsWith("_._", StringComparison.Ordinal))
                    continue;

                var relPath = assemblyRef.Replace('/', Path.DirectorySeparatorChar);

                foreach (var folder in packageFolders)
                {
                    var fullPath = Path.Combine(folder, packagePath, relPath);
                    if (File.Exists(fullPath))
                    {
                        paths.Add(fullPath);
                        break;
                    }
                }
            }
        }

        return paths;
    }

    /// <summary>
    /// Resolves native library paths from the <c>runtimeTargets</c> section of the
    /// assets file. This is more reliable than filesystem scanning because NuGet has
    /// already determined which native assets apply to the current platform.
    /// </summary>
    private static IReadOnlyList<string> ResolveNativePaths(
        Dictionary<string, TargetPackage> target,
        Dictionary<string, LibraryEntry> libraries,
        HashSet<string> included,
        List<string> packageFolders,
        IReadOnlyList<string> rids)
    {
        var paths = new List<string>();

        foreach (var key in included)
        {
            if (!target.TryGetValue(key, out var pkg) || pkg.RuntimeTargets == null)
                continue;

            if (!libraries.TryGetValue(key, out var lib))
                continue;

            var packagePath = lib.Path?.Replace('/', Path.DirectorySeparatorChar)
                              ?? key.Replace('/', Path.DirectorySeparatorChar);

            // Find the best matching RID for native assets in this package
            var bestRid = rids.FirstOrDefault(rid =>
                pkg.RuntimeTargets.Any(rt =>
                    rt.Value.AssetType == "native" &&
                    string.Equals(rt.Value.Rid, rid, StringComparison.OrdinalIgnoreCase)));

            if (bestRid == null)
                continue;

            foreach (var rt in pkg.RuntimeTargets)
            {
                if (rt.Value.AssetType != "native" ||
                    !string.Equals(rt.Value.Rid, bestRid, StringComparison.OrdinalIgnoreCase))
                    continue;

                var relPath = rt.Key.Replace('/', Path.DirectorySeparatorChar);

                foreach (var folder in packageFolders)
                {
                    var fullPath = Path.Combine(folder, packagePath, relPath);
                    if (File.Exists(fullPath))
                    {
                        paths.Add(fullPath);
                        break;
                    }
                }
            }
        }

        return paths;
    }

    /// <summary>
    /// Returns runtime identifier candidates in preference order for the current platform.
    /// More specific RIDs (e.g. win-x64) are tried before generic ones (e.g. win).
    /// </summary>
    private static IReadOnlyList<string> GetRuntimeIdentifierCandidates()
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            return RuntimeInformation.ProcessArchitecture switch
            {
                Architecture.X64   => ["win-x64",   "win"],
                Architecture.X86   => ["win-x86",   "win"],
                Architecture.Arm64 => ["win-arm64", "win"],
                _                  => ["win"]
            };
        }

        if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            return RuntimeInformation.ProcessArchitecture switch
            {
                Architecture.Arm64 => ["osx-arm64", "osx"],
                _                  => ["osx-x64",   "osx"]
            };
        }

        // Linux
        return RuntimeInformation.ProcessArchitecture switch
        {
            Architecture.X64   => ["linux-x64",   "linux"],
            Architecture.Arm64 => ["linux-arm64", "linux"],
            _                  => ["linux"]
        };
    }

    // ── JSON model ────────────────────────────────────────────────────────────

    private sealed class AssetsFile
    {
        [JsonPropertyName("version")]
        public int Version { get; init; }

        [JsonPropertyName("targets")]
        public Dictionary<string, Dictionary<string, TargetPackage>> Targets { get; init; } = [];

        [JsonPropertyName("libraries")]
        public Dictionary<string, LibraryEntry> Libraries { get; init; } = [];

        [JsonPropertyName("packageFolders")]
        public Dictionary<string, JsonElement> PackageFolders { get; init; } = [];
    }

    private sealed class TargetPackage
    {
        [JsonPropertyName("type")]
        public string? Type { get; init; }

        [JsonPropertyName("dependencies")]
        public Dictionary<string, string>? Dependencies { get; init; }

        [JsonPropertyName("compile")]
        public Dictionary<string, JsonElement>? Compile { get; init; }

        [JsonPropertyName("runtime")]
        public Dictionary<string, JsonElement>? Runtime { get; init; }

        /// <summary>
        /// RID-specific assets, keyed by relative path within the package.
        /// Each entry has an assetType ("runtime" or "native") and a rid.
        /// Used for platform-specific managed dlls and native libraries.
        /// </summary>
        [JsonPropertyName("runtimeTargets")]
        public Dictionary<string, RuntimeTarget>? RuntimeTargets { get; init; }
    }

    private sealed class RuntimeTarget
    {
        [JsonPropertyName("assetType")]
        public string? AssetType { get; init; }

        [JsonPropertyName("rid")]
        public string? Rid { get; init; }
    }

    private sealed class LibraryEntry
    {
        [JsonPropertyName("path")]
        public string? Path { get; init; }
    }
}

/// <summary>
/// The result of a NuGet resolution operation.
/// </summary>
public sealed class NuGetResolutionResult
{
    public static readonly NuGetResolutionResult Empty =
        new([], []);

    /// <summary>
    /// Absolute paths to managed assemblies. Pass these to Roslyn as metadata
    /// references and to <see cref="TemplateRunnerOptions.AdditionalReferencePaths"/>.
    /// </summary>
    public IReadOnlyList<string> ManagedAssemblyPaths { get; }

    /// <summary>
    /// Absolute paths to native libraries found in <c>runtimes/{rid}/native/</c>
    /// folders. Pass these to <see cref="TemplateRunnerOptions.NativeLibraryPaths"/>
    /// so the load context can resolve P/Invoke calls.
    /// </summary>
    public IReadOnlyList<string> NativeLibraryPaths { get; }

    public NuGetResolutionResult(
        IReadOnlyList<string> managedAssemblyPaths,
        IReadOnlyList<string> nativeLibraryPaths)
    {
        ManagedAssemblyPaths = managedAssemblyPaths;
        NativeLibraryPaths   = nativeLibraryPaths;
    }
}

/// <summary>
/// Thrown when NuGet package resolution fails.
/// </summary>
public sealed class NuGetResolutionException : CsTemplateException
{
    public NuGetResolutionException(string message) : base(message) { }
    public NuGetResolutionException(string message, Exception inner) : base(message, inner) { }
}
